let classes = [
  {
    id: 1001,
    subject: "Math",
    location: "Qusais",
    price: 150,
    spaces: 5,
    img: "images/math.png",
    dSpace: 5,
  },
  {
    id: 1002,
    subject: "Science",
    location: "Abu Hail",
    price: 200,
    spaces: 5,
    img: "images/science.jpg",
    dSpace: 5,
  },
  {
    id: 1003,
    subject: "English",
    location: "Deira",
    price: 250,
    spaces: 5,
    img: "images/english.jpg",
    dSpace: 5,
  },
  {
    id: 1004,
    subject: "Social Science",
    location: "Abu Hail",
    price: 150,
    spaces: 5,
    img: "images/social_studies.jpg",
    dSpace: 5,
  },
  {
    id: 1005,
    subject: "Business Studies",
    location: "Deira",
    price: 300,
    spaces: 5,
    img: "images/business.jpg",
    dSpace: 5,
  },
  {
    id: 1006,
    subject: "Marketing",
    location: "Qusais",
    price: 150,
    spaces: 5,
    img: "images/marketing.png",
    dSpace: 5,
  },
  {
    id: 1007,
    subject: "Robotics",
    location: "Barsha",
    price: 350,
    spaces: 5,
    img: "images/robotics.jpg",
    dSpace: 5,
  },
  {
    id: 1008,
    subject: "Advanced Math",
    location: "Abu Hail",
    price: 400,
    spaces: 5,
    img: "images/adv_math.jpg",
    dSpace: 5,
  },
  {
    id: 1009,
    subject: "Economics",
    location: "Deira",
    price: 150,
    spaces: 5,
    img: "images/economics.png",
    dSpace: 5,
  },
  {
    id: 1010,
    subject: "Islamic",
    location: "Barsha",
    price: 200,
    spaces: 5,
    img: "images/islamic.jpg",
    dSpace: 5,
  },
];
